version: '3'
services:
  redis:
      image: wangyongdong/docker-redis:latest
      ports:
        - "36362:6379"
      networks:
        - net-redis
      volumes:
        - ./data/redis/data:/data                                     # data dir
        - ./data/redis/conf/redis.conf:/usr/local/redis/redis.conf    # Configuration file
        - ./data/redis/logs/redis.log:/usr/local/logs/redis.log       # logs file
      restart: always
      container_name: antDP-redis

  mysql:
      depends_on:
        - redis
      image: wangyongdong/docker-mysql:latest
      ports:
        - "3362:3306"
      networks:
        - net-mysql
      volumes:
        - ./data/mysql/data:/var/lib/mysql        # data dir
        - ./data/mysql/logs:/var/log/mysql        # errlog and slowquery
        - ./data/mysql/conf:/etc/mysql            # Configuration file
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      restart: always
      container_name: antDP-mysql

  php:
      depends_on:
        - mysql
      image: wangyongdong/docker-php:latest
      ports:
        - "9062:9000"
#      links:
#        - "mysql"
#        - "redis"
      networks:
            - net-php
            - net-mysql
            - net-redis
      volumes:
        - ./data/php/conf/php.ini:/etc/php7/php.ini
        - ./data/php/conf/php-fpm.conf:/etc/php7/php-fpm.conf
        - ./data/php/conf/www.conf:/etc/php7/php-fpm.d/www.conf
        - ./data/php/logs/error.log:/etc/php7/logs/error.log
        - ./data/www:/usr/local/nginx/html
      restart: always
      container_name: antDP-php

  nginx:
      depends_on:
        - php
      image: wangyongdong/docker-nginx:latest
      ports:
        - "8062:80"
        - "4462:443"
#      links:
#        - "php"
      networks:
        - net-php
      volumes:
        - ./data/www:/usr/local/nginx/html
        - ./data/nginx/logs:/usr/local/nginx/logs
        - ./data/nginx/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
        - ./data/nginx/conf/vhost:/usr/local/nginx/conf/vhost
        - ./data/nginx/cert:/usr/local/nginx/cert
      restart: always
      container_name: antDP-nginx

  nodejs:
        depends_on:
          - nginx
        image: wangyongdong/docker-nodejs:latest
        ports:
          - "3062:3000"
        networks:
          - net-nodejs
        volumes:
          - ./data/www:/app/src
        restart: always
        container_name: antDP-nodejs

networks:
  net-php:
  net-mysql:
  net-redis:
  net-nodejs:
